bullet.pubsub.context.name: "QUERY_SUBMISSION"
bullet.pubsub.class.name: "com.yahoo.bullet.pubsub.rest.RESTPubSub"
# We have to use the IdentityPubSubMessageSerDe because we use asJSON and fromJSON to convert back and forth in the RestPubSub
bullet.pubsub.message.serde.class.name: "com.yahoo.bullet.pubsub.IdentityPubSubMessageSerDe"
# In-Memory pubsub settings that you may change for each instance (there may be multiple in-memory pubsub instances)
# The paths (not including the context.path) of the endpoints for reading/writing queries/responses
bullet.pubsub.rest.query.urls:
    - "http://localhost:9999/api/bullet/pubsub/query"
bullet.pubsub.rest.result.url: "http://localhost:9999/api/bullet/pubsub/result"
# Http connection timout for subscribers
bullet.pubsub.rest.subscriber.connect.timeout.ms: 5000
# Http connection timout for publishers
bullet.pubsub.rest.publisher.connect.timeout.ms: 5000
# Maximum number of uncommitted messages allowed before read requests will wait for commits (used by both the web service and the backend)
bullet.pubsub.rest.subscriber.max.uncommitted.messages: 100
# Minimum time (ms) between http calls to the result subscriber REST endpoint
bullet.pubsub.rest.result.subscriber.min.wait.ms: 10
# Minimum time (ms) between http calls to the query subscriber REST endpoint
bullet.pubsub.rest.query.subscriber.min.wait.ms: 10
